Repository Amarjha01/DevNotes, pull requests merged in 2025-08, with the labels that each got.

#27 feat: Add Contact form and FAQ sections to Home page
  src/pages/Home.jsx
Labels: enhancement, GSSoC25, level2

#86 add favourites feature to projects
  src/pages/Projects.jsx
Labels: GSSoC25, level2

#102 added backend prep sheet
  src/components/backend/BackendPrepSheet.jsx
  src/components/gloable/Header.jsx
  src/routes/routes.jsx
Labels: GSSoC25, level2

#122 added ml/ai prepsheet
  src/components/gloable/Header.jsx
  src/components/machineLearning/MLAIPrepSheet.jsx
  src/routes/routes.jsx
Labels: GSSoC25, level2

#130 Update navigation behavior to redirect to first child path if available ISSUE #127
  src/components/gloable/Header.jsx
Labels: GSSoC25, level1
